name: Build Big Sur Binaries

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-11

    env:
      AUTO_TARGET: "11"
      AUTO_QC:     "Skip"
      TERM:        "xterm-256color"

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies
        run: /bin/zsh Dependencies.tool
      - name: Build
        run: /bin/zsh Build.tool

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: Big-Sur-Binaries
          path: Build/11