name: Build Monterey Binaries

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-12

    env:
      AUTO_TARGET: "12"
      AUTO_QC:     "Skip"
      TERM:        "xterm-256color"

    steps:
      - uses: actions/checkout@v3

      - name: Fetch dependencies
        run: /bin/zsh Dependencies.tool
      - name: Build
        run: /bin/zsh Build.tool

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: Monterey-Binaries
          path: Build/12