name: Check code style

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
